run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    - paralleltest
    - tenv
    - varnamelen
    - mnd
    - exhaustruct
    - forbidigo
    - depguard
    - gofumpt
    - gci
