name: Build and Release Go Binaries

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

defaults:
  run:
    working-directory: ./server

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache-dependency-path: |
            server/go.sum

      - name: Build Go binary
        run: |
          architectures=("arm" "arm64")
          os="linux"
          mkdir -p build  
          repo_name=${{ github.repository }}
          repo_name=${repo_name#*/}

          for arch in "${architectures[@]}"; do
            CGO_ENABLED=0 GOOS=$os GOARCH=$arch go build -o build/${repo_name}-${os}-${arch} -ldflags '-w -s' .
            tar -czf build/${repo_name}-${os}-${arch}.tar.gz -C build ${repo_name}-${os}-${arch} --transform "s|${repo_name}-${os}-${arch}|${repo_name}|"
          done

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: server/build/*.tar.gz
