name: Build and Release Go Binaries

on:
  push:
    tags:
      - "v*"
    branches:
      - main

permissions:
  contents: read

defaults:
  run:
    working-directory: ./server

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux] # Поддерживаем несколько операционных систем
        goarch: [armv7, arm64] # Архитектуры для Raspberry Pi (32-бит и 64-бит)
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache-dependency-path: |
            server/go.sum

      - name: Build Go binary
        run: |
          mkdir -p build  
          CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build/${{ github.repository }} -ldflags '-w -s' .

      - name: Create tar.gz archive
        run: |
          cd build
          tar -czf ${{ github.repository }}-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz ${{ github.repository }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: go-build-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/${{ github.repository }}-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz

  release:
    runs-on: ubuntu-latests
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
